// import React from 'react'

function Terms() {
  return (
    <section className="max-w-screen-lg mx-auto text-white">
      <div className="mt-[100px] px-[15px]">
        <h1 className="text-[25px] font-semibold text-center ">
          TERMS AND CONDITIONS FOR THE USER AS PER LAW
        </h1>
        <p className="pt-[40px] text-[16px]">
          The law of land made provisions to draft the Terms and Conditions,
          Privacy policy, and Cookies policy to use the Internet of things. We,
          following the provisions of Rule 3 and 4 of the Information Technology
          (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021,
          and are an ‘electronic record’ as contemplated under section 2(t) of
          the Information Technology Act, 2000 and the Rules there under. These
          Terms being an electronic record are generated by a computer system
          and do not require any physical or digital signatures.
        </p>
        <h2 className="text-[25px] pt-[20px]">DIGEST OF THE DRAFT</h2>
        <p className="text-[16px] pt-[10px]">
          The Platform “ZYRO” has been introduced by KGC Infotech Pvt. Ltd
          itself, a Private Limited Firm having its office at 804 Grandslam
          Ithum Tower, Tower A, Noida, Uttar Pradesh 201309, India, (hereinafter
          referred to as &#34;Owner&#34;, “We”, “ZYRO” or “Us”) to facilitate
          online banking services in which ZYRO provide services related to
          corporate cards and payment solutions to the customers.
        </p>

        <h2 className="text-[25px] pt-[20px]">ENTRANCE TO THE PLATFORM</h2>
        <p className="text-[16px] pt-[10px]">
          That ZYRO and the website https://zyro.in/ is owned by KGC Infotech
          Pvt. Ltd. Any person using the said website/link/platform is known as
          User (hereinafter referred to as “You”, “Merchant” or “User”).
        </p>
        <p className="text-[16px] pt-[10px]">
          That Users are being authorized to use the ZYRO website or any other
          linked pages, API keys, features, content or application services
          (including but not limited to any mobile application or site services)
          (hereinafter referred to as “Platform”) as per terms and conditions
          set out in the present draft. If any user is browsing, accessing, or
          otherwise using the platform, it will be presumed as your irrevocable
          and unequivocal acceptance and acknowledgment of the terms and
          conditions and policies thereof.{" "}
        </p>
        <p className="text-[16px] pt-[10px]">
          You the user shall read the terms and conditions of the
          agreement/draft before using the platform. If you start using our
          platform then we will presume/understand that you have read the term
          and condition established by us well and have given your consent in
          it. You the user shall be contracting with these terms and conditions
          as set out including the policies constitute your binding obligations
          with ZYRO.{" "}
        </p>
        <p className="text-[16px] pt-[10px]">
          It is the discretion of ZYRO to allow or disallow you the user to
          access the platform. ZYRO also reserve the right of changing any of
          the terms and conditions contained herein at any point of time. You
          the user is responsible to periodically review any changes and update
          in the terms of use by ZYRO. If you the user continue to use the
          platform without review of the update, it shall be considered your
          acceptance to such updates and change.
        </p>
        <h2 className="text-[25px] pt-[20px]">APPLICABILITY OF LAWS </h2>
        <p className="text-[16px] pt-[10px]">
          You the user of the platform shall be obliged by all applicable laws
          of the land.{" "}
        </p>
        <h3 className="text-lg font-semibold pt-[20px]">
          The term “Applicable Laws” means;
        </h3>
        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            any law, act, rule and regulation/circular, order/decree, judgment,
            decision, directive or other similar mandates of any applicable
            central, national, state or local governmental/regulatory Authority
            having competent jurisdiction and force of law over, or applicable
            to You the user, us or the subject matter in question, as may be
            which is amended from time to time;
          </li>
          <li className="text-[16px] pt-[10px]">
            shall without limitation include any notification, circular,
            directive or other similar instruction issued by the ‘Financial
            Sector Regulators’ including but not limited to the Reserve Bank of
            India (RBI) and/or rules, regulations, roles, responsibilities and
            processes as defined by NPCI on their website www.npci.org.in.
          </li>
        </ol>

        <h2 className="text-[25px] pt-[20px]">USER ACCOUNT </h2>
        <p className="text-[16px] pt-[10px]">
          That user can create free account on the platform. The fees policy can
          be changed in future by ZYRO. Such change shall be posted on the
          Platform and shall immediately become effective. Unless otherwise
          stated, all fees shall be quoted in Indian Rupees. Using and accessing
          the platform is free of cost. But ZYRO reserves its right to charge
          cost from the user at anytime in future.{" "}
        </p>
        <h2 className="text-[25px] pt-[20px]">COMMUNICATIONS</h2>
        <p className="text-[16px] pt-[10px]">
          That to use the platform, the user needs to provide a valid email
          address and/or phone number. Any message sent by Whatsapp, email
          address, phone number, SMS or any one other medium to the platform by
          the user, it amounts to a valid consent from the user. ZYRO can use
          such provided information for sending SMS/ notifications/any other
          information to the user which may be related to our services updates
          or otherwise. That the user signing in on the platform is a kind of
          implied consent in favour of the owner for use of data/information for
          communication purpose or otherwise. There is no infringement of any
          legal or statutory right of the user in using of such information/data
          by the owner because the user consented for the same; hence for using
          such data/information no claim will be maintainable against the owner.{" "}
        </p>
        <h2 className="text-[25px] pt-[20px]">SEVERABILITY:</h2>
        <p className="text-[16px] pt-[10px]">
          Each of the provisions in these terms are severable and distinct from
          the others and if at any time one or more such provisions become
          invalid, illegal or unenforceable, the validity, legality and
          enforceability of the remaining provisions of these Terms shall not in
          any way be affected or impaired thereby.
        </p>
        <h2 className="text-[25px] pt-[20px]">FORCE MAJEURE</h2>
        <p className="text-[16px] pt-[10px]">
          Notwithstanding anything contained in these Terms or elsewhere, ZYRO
          shall not be held responsible for any loss, damage if such loss,
          damage is attributable to a Force Majeure Event.
        </p>
        <p className="text-[16px] pt-[10px]">
          A &#34;Force Majeure means any event that is beyond ZYRO reasonable
          control and includes, without limitation, fire, flood, explosion, acts
          of God, civil commotion, strikes, lock outs or industrial action of
          any kind, riots, insurrection, terrorist attacks, war, acts of
          government, power failure, sabotage, computer hacking, unauthorized
          access to computer data and storage device, system failure, virus,
          attacks, bugs, computer crashes, breach of security and encryption.
        </p>
        <h2 className="text-[25px] pt-[20px]">DISPUTES</h2>
        <p className="text-[16px] pt-[10px]">
          Regarding any kind of complaints relating to the services taken from
          our platform by the user, ZYRO will be responsible to resolve the same
          complaint which may be raised by the user. That, the owner of the
          platform shall not be responsible for ensuring resolution of the
          complaints on any losses as and shall not be in any manner either
          directly or indirectly be liable for any claims or proceedings made by
          any user in relation to the services provided on or through the
          platform or otherwise.{" "}
        </p>
        <h2 className="text-[25px] pt-[20px]">INTELLECTUAL PROPERTY RIGHT</h2>
        <p className="text-[16px] pt-[10px]">
          The intellectual property right law shall be protected. We look
          forward to protecting the rights hence all content on the platform
          like; text, graphics, logos, button icons, images, audio data
          compilations, brand name, software, SoftPos devise, technology,
          documentation, manuals, etc is the property of ZYRO and any portion of
          the platform cannot be produced/reproduced and used anywhere else
          without the prior consent of the owner. It may be related to
          Trademark, copyright and patent. The trademarks, logos and service
          marks displayed on the website/link/application/platform are the
          properties of ZYRO or its affiliates, associates or its content
          suppliers or users or respective third parties.
        </p>

        <p className="text-[16px] pt-[10px]">
          Users are not permitted to use the Marks without the prior consent and
          terms and conditions levied by ZYRO or the actual owner of the
          intellectual property.
        </p>

        <p className="text-[16px] pt-[10px]">
          That the ZYRO is the owner of all content of copyright, patents,
          utility models, designs, know-how, softwares, applications, trade
          secrets and inventions, goodwill, source code, meta tags, databases,
          text, content, graphics, icons, and hyperlinks. The user shall not
          use, copy, reproduce, modify, alter, change, amend, transmit,
          broadcast, edit, revise, review, adapt, translate, distribute,
          perform, display, sell or otherwise.
        </p>

        <p className="text-[16px] pt-[10px]">
          If Users or publish use any image, graphics, mark, logo, design and
          other intellectual property which he did not own, without prior
          permission of the actual owner, the user shall only be responsible for
          the loss/damage if any caused to the real owner of such property. The
          owner of the platform cannot be held liable for the same. We do not
          support any such act which infringes legal rights of others.
        </p>
        <h2 className="text-[25px] pt-[20px]">DISCLAIMER</h2>
        <p className="text-[16px] pt-[10px]">
          You the user agree that you are using the platform at your own risk.
          The contents made available by the user and uploaded or provided or
          shared on the platform as it is and as available and no
          changes/modification has been done to such content and information
          hence, without any warranty of any kind whether express, implied,
          statutory or otherwise, including the implied warranties of title,
          non-infringement, suitability, accuracy, reliability, completeness,
          timeliness, performance, safety, merchantability or fitness for a
          particular purpose or the legality of the products listed or displayed
          or transacted to the extent permitted by applicable Indian law and
          ZYRO does not accept any liability for any errors or omissions.
        </p>
        <h3 className="text-lg font-semibold pt-[20px]">LIMITATION OF LIABILITY </h3>
        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            Notwithstanding anything stated under this Agreement including the
            obligation to indemnify the Merchant, the aggregate liability of
            ZYRO to the Merchant from any cause whatsoever shall not, in any
            event, exceed the sum equivalent to the preceding one (1) month’s
            aggregate Consideration earned by ZYRO under this agreement from the
            date of occurrence of such liability.
          </li>

          <li className="text-[16px] pt-[10px]">
            Provided that ZYRO shall not be liable to the Merchant for any
            special, incidental, indirect or consequential or direct damages,
            damages from loss of profits or business opportunities even if the
            Merchant shall have been advised in advance of the possibility of
            such loss, cost or damages.
          </li>

          <li className="text-[16px] pt-[10px]">
            In no event shall the Escrow/Nodal Bank or the Acquiring Bank be
            liable to the Merchant in relation to this Terms & Conditions or in
            relation to any claim by a third party.
          </li>

          <li className="text-[16px] pt-[10px]">
            In no event shall ZYRO be liable to the Customers or any third
            party.
          </li>

          <li className="text-[16px] pt-[10px]">
            The ZYRO shall not be liable for any of the following: (a) about
            which it did not have any knowledge; (b) shall not be liable for any
            Net Quantifiable Financial Benefit that arises to the Merchant for
            any loss suffered. The term Net Quantifiable Financial Benefit shall
            include an amount for which Merchant would otherwise have been
            accountable to be assessed for taxation is reduced or extinguished
            because of the matter giving rise to such loss. (c) contingent
            liability of the Merchant unless such liability becomes due and
            payable; (d) Merchant shall not be entitled to recover for the same
            event twice; (f) the amount that is recoverable by the Merchant from
            an insurance policy or from third parties; (g) the amount for which
            provision, allowance, or reserve has been made.
          </li>

          <li className="text-[16px] pt-[10px]">
            The Parties shall have rights to mitigate the losses or damages or
            claims of indemnities either from the Party to the Agreement or from
            third parties. Parties shall be within their rights to terminate the
            Agreement without any notice by written communication to mitigate
            their losses or damages.
          </li>

          <li className="text-[16px] pt-[10px]">
            The owner, its executives, partners, employees and associates shall
            not be liable for any loss or damage whatsoever including without
            limitation direct, indirect, punitive, incidental and consequential
            damages, loss, profits, or damages resulting from the use or
            inability to use the website/link/platform.
          </li>
        </ol>

        <h2 className="text-[25px] pt-[20px]">INDEMNITY</h2>

        <p className="text-[16px] pt-[10px]">
          The user agrees to indemnify harm to each other and put ZYRO and its
          executive, partners, shareholders, employees out of the purview. The
          clause of indemnity is valid even after the termination of the
          agreement.
        </p>

        <p className="text-[16px] pt-[10px]">
          ZYRO has no liability in the event of any action, losses, damages,
          proceedings, claims, and costs (including attorney fees) and other
          expenses suffered or incurred due to or attributable to or arising out
          of:
        </p>

        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            Violation of any applicable law;
          </li>
          <li className="text-[16px] pt-[10px]">
            Breach of any representations or covenants of the User;
          </li>
          <li className="text-[16px] pt-[10px]">
            Breach of the policies, guidelines and conditions of ZYRO or
            Additional Terms or these Terms or Privacy Policy (including any
            modifications or additional notifications or instructions);
          </li>
          <li className="text-[16px] pt-[10px]">
            Infringement of any third party rights.
          </li>
        </ol>
        <h2 className="text-[25px] pt-[20px]">
          VIOLATION OF THESE TERMS OF USE
        </h2>

        <p className="text-[16px] pt-[10px]">
          ZYRO may disclose any information we have about you (including your
          identity) for connection with any investigation or complaint regarding
          your use of the platform, or to identify, contact or bring legal
          action against someone who may be causing injury to or interference
          with (either intentionally or unintentionally), if we determine that
          such disclosure is necessary.
        </p>

        <p className="text-[16px] pt-[10px]">
          You the user accepts and agree that ZYRO may preserve any transmittal
          or communication by you with ZYRO through the platform and may also
          disclose such data if required to do so by law or ZYRO determines that
          such preservation or disclosure is reasonably necessary to:
        </p>

        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">Comply with legal process;</li>
          <li className="text-[16px] pt-[10px]">Enforce these Terms of Use;</li>
          <li className="text-[16px] pt-[10px]">
            Respond to claims that any such data violates the rights of others;
          </li>
          <li className="text-[16px] pt-[10px]">
            Protect the rights, property or personal safety of ZYRO, its
            employees, users of or visitors to the Site/Platform, and the
            public.
          </li>
        </ol>

        <p className="text-[16px] pt-[10px]">
          You the user agree that ZYRO may, in its sole discretion and without
          prior notice, terminate your access to the platform and/or block your
          future access to the ZYRO if it thinks that you have violated such
          Terms of Use or other agreements or guidelines which may be associated
          with your use of the platform. You also agree that any violation by
          you of these Terms of Use will constitute an unlawful and unfair
          business practice, and will cause irreparable harm to ZYRO, for which
          monetary damages would be inadequate, and you consent to ZYRO
          obtaining any injunctive or equitable relief that ZYRO deems necessary
          or appropriate in such circumstances.
        </p>

        <p className="text-[16px] pt-[10px]">
          You agree that ZYRO may, in its sole discretion and without prior
          notice, terminate your access to the platform, for cause, which
          includes (but is not limited to):
        </p>

        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            Requests by law enforcement or other government agencies;
          </li>
          <li className="text-[16px] pt-[10px]">
            A request by you (self-initiated account deletions);
          </li>
          <li className="text-[16px] pt-[10px]">
            Discontinuance or material modification of the Platform or any
            service offered on or through the Platform;
          </li>
          <li className="text-[16px] pt-[10px]">
            Unexpected technical issues or problems.
          </li>
        </ol>
        <h2 className="text-[25px] pt-[20px]">TERMINATION</h2>

        <p className="text-[16px] pt-[10px]">
          ZYRO reserves the right to terminate the services of the platform
          provided to any user without prior notice in the event of any default
          committed by the user including but not limited to the breach of any
          applicable law, policies, guidelines and conditions of ZYRO’s service
          or terms and conditions set down by the owner.
        </p>

        <p className="text-[16px] pt-[10px]">
          The owner can terminate the user account if the user is not useful for
          the owner in the business. Notwithstanding anything to the contrary,
          ZYRO shall have the right to immediately suspend Services and
          settlement of any monies or payments to You, without any liability to
          You, in the event of the following:
        </p>

        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            You breach any clause of these Terms.
          </li>
          <li className="text-[16px] pt-[10px]">
            You facilitate any transaction which is unlawful or in contravention
            of the Prohibited Products and Services.
          </li>
          <li className="text-[16px] pt-[10px]">
            ZYRO receives instructions from Facility Providers or governmental
            authorities or law enforcement agencies to either suspend the
            Services, or part thereof, regardless of whether there is a pending
            investigation/inquiry into any alleged illegal/unlawful activities.
          </li>
          <li className="text-[16px] pt-[10px]">
            You use the Services for any transactions which have a high-risk
            score as per ZYRO’s internal fraud assessment tools and other
            policies.
          </li>
          <li className="text-[16px] pt-[10px]">
            ZYRO is of the opinion that there are suspicious circumstances
            surrounding your activities.
          </li>
          <li className="text-[16px] pt-[10px]">
            ZYRO is of the opinion that there is pending, anticipated, or
            excessive disputes, refunds, or reversals relating to your use of
            Services.
          </li>
          <li className="text-[16px] pt-[10px]">
            Your products/services infringe, or are suspected of infringing,
            intellectual property rights, copyrightable works, patented
            inventions, trademarks, and trade secrets, or you are suspected of
            selling counterfeit and/or knock-off goods.
          </li>
          <li className="text-[16px] pt-[10px]">
            You materially change the type of the products/services provided to
            end customers and as declared on the onboarding form, without
            obtaining ZYRO’s prior written permission to use the Services for
            the new or changed types of services/products, or it is discovered
            by ZYRO that you provided substantially misleading and/or false
            information about your products/services as part of the onboarding
            activities.
          </li>
          <li className="text-[16px] pt-[10px]">
            ZYRO in its sole discretion determines that your activities expose
            ZYRO to risks that are unacceptable to ZYRO.
          </li>
          <li className="text-[16px] pt-[10px]">
            ZYRO in its sole discretion is required to do so due to regulatory
            changes impacting the Services.
          </li>
        </ol>

        <p className="text-[16px] pt-[10px]">
          After termination of the account, the owner can store and use the
          data, information, or any other information which has been stored in
          our server. If ZYRO does take any legal action against you as a result
          of your violation of these Terms of Use, ZYRO will be entitled to
          recover any loss from you, and you agree to pay all reasonable costs
          arising out of such set-off, in addition to any other relief granted
          to ZYRO.
        </p>

        <p className="text-[16px] pt-[10px]">
          You agree that ZYRO will not be liable to you or any third party for
          termination of your access to the Platform as a result of any
          violation of these Terms of Use.
        </p>

        <h2 className="text-[25px] pt-[20px]">
          PAYMENTS, CHARGEBACKS, AND REFUNDS
        </h2>

        <p className="text-[16px] pt-[10px]">
          The transfer of the Customer’s payment to the Merchant by ZYRO shall
          be governed by the following terms:
        </p>

        <p className="text-[16px] pt-[10px]">
          Subject to applicable law, payments shall be made available by ZYRO to
          the Merchant after making the following adjustments, deductions, and
          any other deductions in terms of this Agreement from the amount of the
          Transaction (subject to the volumes/limits allowed to the Merchant):
        </p>

        <ul className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            The consideration/fees, the TDR along with other dues, fees,
            charges, out-of-pocket expenses, etc., due to ZYRO in terms of
            Schedule I of this Agreement or at any other rates and percentage as
            amended from time to time for all Transactions processed.
          </li>
          <li className="text-[16px] pt-[10px]">
            Sum of all customer charges denied, refused, or charged back by the
            customer/partner banks.
          </li>
          <li className="text-[16px] pt-[10px]">
            All costs, charges, expenses, etc., on account of inquiries,
            disputes, cancellations, and/or refunds processed on account of
            Merchant’s customer charges and/or chargeback. Refunds and
            chargeback recovery shall be done at the gross amount, and any
            applicable convenience fees or exchange rate fluctuations shall be
            borne by the Merchant.
          </li>
          <li className="text-[16px] pt-[10px]">
            Any taxes, including but not limited to goods and service tax,
            service tax, education cess, swachh bharat cess, penalties, charges,
            or other items reimbursable under any provision of this Agreement,
            or otherwise.
          </li>
        </ul>

        <p className="text-[16px] pt-[10px]">
          ZYRO shall reconcile the accounts and make payments to the Merchant
          subject to ZYRO’s right to withhold payments for any charges or
          chargeback recovery/debits that may be fraudulently incurred,
          suspicious transactions, or for any reason permissible under
          applicable law. Payments withheld will be released once ZYRO
          determines such charge/debit is valid. The Merchant shall indemnify
          ZYRO for losses if ZYRO is unable to withhold payment in respect of
          suspected fraudulent charge/debit.
        </p>

        <p className="text-[16px] pt-[10px]">
          Payments by ZYRO to the Merchant shall be without prejudice to any
          claims or rights ZYRO may have against the Merchant, and shall not
          constitute an admission of the Merchant’s performance under this
          Agreement.
        </p>

        <p className="text-[16px] pt-[10px]">
          If required, the Merchant shall provide further assurances,
          guarantees, or security as specified by ZYRO. ZYRO may set off claims
          against the security deposit in the event of:
        </p>

        <ol className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            Any material breach of the terms of this Agreement.
          </li>
          <li className="text-[16px] pt-[10px]">
            ZYRO being unable to withhold payment in respect of suspected
            fraudulent charge/debit.
          </li>
          <li className="text-[16px] pt-[10px]">
            The existence of other claims against the Merchant.
          </li>
        </ol>

        <p className="text-[16px] pt-[10px]">
          Payment timeline: Upon completion of the Transaction and receipt of
          funds by ZYRO, and where applicable, on receipt of proof of delivery,
          ZYRO shall make payments to the Merchant within the later of (i) two
          business days from receipt of funds or (ii) the maximum period allowed
          under applicable regulations.
        </p>

        <p className="text-[16px] pt-[10px]">
          Payment by ZYRO, where set-offs could not be exercised, shall not
          waive its rights to recover amounts payable by the Merchant or to seek
          indemnities.
        </p>

        <p className="text-[16px] pt-[10px]">
          ZYRO may recover amounts for reasons including:
        </p>

        <ul className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            Any unlawful or unenforceable Transaction.
          </li>
          <li className="text-[16px] pt-[10px]">
            Information not received as per ZYRO’s requirements.
          </li>
          <li className="text-[16px] pt-[10px]">
            Transactions outside authorized territory.
          </li>
          <li className="text-[16px] pt-[10px]">
            Transactions posted more than once to the cardholder’s account.
          </li>
          <li className="text-[16px] pt-[10px]">
            Transactions doubtful or erroneously paid to the Merchant.
          </li>
        </ul>

        <p className="text-[16px] pt-[10px]">
          If non-compliance results in losses to ZYRO, the Merchant shall bear
          all charges, interest, and costs. Uncollectable charges shall be the
          Merchant’s sole responsibility, and ZYRO may process chargebacks
          without protest.
        </p>

        <p className="text-[16px] pt-[10px]">
          ZYRO reserves the right to suspend payments if the Merchant is
          suspected of breach, misrepresentation, or fraud, and may debit the
          Merchant’s account for:
        </p>

        <ul className="list-decimal pl-5">
          <li className="text-[16px] pt-[10px]">
            Chargebacks of Transactions.
          </li>
          <li className="text-[16px] pt-[10px]">
            Penalties, charges, or claims, including legal claims, arising from
            excessive chargebacks, failed transactions, or customer disputes.
          </li>
          <li className="text-[16px] pt-[10px]">
 ZYRO shall not be liable for any chargeback or fraudulent transactions
          by the Merchant.
          </li>
        </ul>

       
  <h2 className="text-[25px] pt-[20px] font-bold">Procedure for Change of Bank Account and Documents Required</h2>

  <h3 className="text-lg font-semibold pt-[20px]">Why Change of Bank Account?</h3>
  <p>
    Most banks in India have migrated to the Core-Banking System (CBS), revising existing account numbers 
    to 15 or 16-digit numbers. Merchants must promptly notify Zyro of any changes and provide the IFSC, 
    following the procedure below.
  </p>
  <p>
    Other reasons for changing bank accounts may include relocation. Merchants must notify Zyro using the 
    prescribed bank mandate form with the new account details and supporting documents.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">Steps to Change Bank Account</h3>
  <ol className="list-decimal pl-6 space-y-2">
    <li>
      Submit the prescribed bank mandate form to ZYRO Support with a cancelled cheque leaf or other documents 
      of the new bank account.
    </li>
    <li>
      Use the stand-alone Change of Bank Mandate form for updating a single account 
      (account holder&#39;s name must appear on the cheque).
    </li>
    <li>
      For multiple accounts, use the “Multiple Bank Account Registration Form” with documents for each account.
    </li>
  </ol>

  <h3 className="text-lg font-semibold">Default Bank Account in Case of Multiple Accounts</h3>
  <p>
    Merchants must specify one account as the default for redemption/refund payments. If no account is 
    specified in a request, payments go to the default account.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">List of Requisite Documents</h3>
  <ol className="list-decimal pl-6 space-y-2">
    <li>
      Cancelled cheque of the new mandate with holder’s name and account number printed; OR
    </li>
    <li>
      Self-attested bank statement/passbook (not older than 3 months); OR
    </li>
    <li>
      Bank letter certifying account details, signed by the branch manager/authorized personnel.
    </li>
  </ol>
  <p>
    Additional documents may be required for old accounts or closed accounts to verify authenticity and 
    prevent fraud.
  </p>

  <h3 className="text-lg font-semibold">Cooling Period</h3>
  <p>
    A cooling period of 3–5 days applies when a bank change request is received alongside or just before 
    a redemption request, to prevent fraud.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">Data Protection</h3>
  <ol className="list-decimal pl-6 space-y-2">
    <li>
      Maintain safeguards equal to or better than industry standards to protect customer information.
    </li>
    <li>
      Protect against unauthorized access, threats, or hazards.
    </li>
    <li>
      Secure disposal of customer data.
    </li>
    <li>
      Report breaches or suspected breaches within 12 hours to ZYRO.
    </li>
  </ol>

  <h3 className="text-lg font-semibold pt-[20px]">Covenants</h3>
  <ol className="list-decimal pl-6 space-y-2">
    <li>
      Users agree to follow Additional Terms, rules, and policies of ZYRO.
    </li>
    <li>
      Content posted must not be false, misleading, or in violation of laws.
    </li>
    <li>
      Objectionable content is prohibited and must be reported immediately.
    </li>
  </ol>

  <h3 className="text-lg font-semibold pt-[20px]">Use of Content</h3>
  <p>
    By posting content, users grant ZYRO the right to use, reproduce, and display it worldwide. 
    Users warrant ownership/control of posted content and that it complies with applicable laws.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">Miscellaneous</h3>
  <ol className="list-decimal pl-6 space-y-2">
    <li>
      ZYRO is not liable for hardware/software compatibility or security issues while using the platform.
    </li>
    <li>
      Invalid or unenforceable provisions do not affect the rest of the Terms.
    </li>
  </ol>

  <h3 className="text-lg font-semibold pt-[20px]">Notices</h3>
  <p>
    Notices must be in writing and delivered by hand, post, or fax. Delivery is deemed after 7 days of posting 
    or upon receipt.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">Assignment</h3>
  <p>
    Merchants cannot assign obligations without ZYRO’s consent. ZYRO can assign its rights to affiliates 
    without consent.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">Privacy Policy</h3>
  <p>
    Using the website constitutes consent to the use of your information as outlined in our Privacy Policy.
  </p>

  <h3 className="text-lg font-semibold pt-[20px]">Grievance Cell</h3>
  <p>
    Contact Grievance Officer at: <a href="mailto:care@ZYRO.in" className="text-blue-600 underline">care@ZYRO.in</a>
  </p>
</div>

     
    </section>
  );
}

export default Terms;
